### ISSUE TITLE
Compilation failing with latest libuv 1.19.1

### ISSUE THREAD

**Issue by torinaki** [bwoebi/php-uv#57]
```
running: phpize
Configuring for:
PHP Api Version:         20170718
Zend Module Api No:      20170718
Zend Extension Api No:   320170718
building in /tmp/pear/temp/pear-build-defaultuservDqrvX/uv-0.2.2
running: /tmp/pear/temp/uv/configure --with-php-config=/usr/local/bin/php-config
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr/local
checking for PHP includes... -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/lib/php/extensions/no-debug-non-zts-20170718
checking for PHP installed headers prefix... /usr/local/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... re2c
checking for re2c version... 0.16 (ok)
checking for gawk... no
checking for nawk... nawk
checking if nawk is broken... no
checking Whether to include "uv" support... yes, shared
checking for uv debug support... no
checking Whether to enable the "dtrace" debug... no
checking for pkg-config... /usr/bin/pkg-config
checking for libuv... from pkgconfig: found version 1.19.1
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for /usr/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking the maximum length of command line arguments... 1572864
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC
checking if cc PIC flag -fPIC works... yes
checking if cc static flag -static works... yes
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
creating libtool
appending configuration tag "CXX" to libtool
configure: creating ./config.status
config.status: creating config.h
running: make
/bin/bash /tmp/pear/temp/pear-build-defaultuservDqrvX/uv-0.2.2/libtool --mode=compile cc  -I. -I/tmp/pear/temp/uv -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuservDqrvX/uv-0.2.2/include -I/tmp/pear/temp/pear-build-defaultuservDqrvX/uv-0.2.2/main -I/tmp/pear/temp/uv -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/usr/local/include  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/temp/uv/php_uv.c -o php_uv.lo
mkdir .libs
 cc -I. -I/tmp/pear/temp/uv -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuservDqrvX/uv-0.2.2/include -I/tmp/pear/temp/pear-build-defaultuservDqrvX/uv-0.2.2/main -I/tmp/pear/temp/uv -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/usr/local/include -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/temp/uv/php_uv.c  -fPIC -DPIC -o .libs/php_uv.o
/tmp/pear/temp/uv/php_uv.c: In function 'php_uv_cb_init_dynamic':
/tmp/pear/temp/uv/php_uv.c:501:31: error: lvalue required as increment operand
    GC_REFCOUNT(cb->fci.object)++;
                               ^~
/tmp/pear/temp/uv/php_uv.c: In function 'php_uv_cb_init':
/tmp/pear/temp/uv/php_uv.c:531:31: error: lvalue required as increment operand
    GC_REFCOUNT(cb->fci.object)++;
                               ^~
/tmp/pear/temp/uv/php_uv.c: In function 'destruct_uv':
/tmp/pear/temp/uv/php_uv.c:1249:4: error: lvalue required as increment operand
    ++GC_REFCOUNT(obj);
    ^~
/tmp/pear/temp/uv/php_uv.c: In function 'php_uv_listen_cb':
/tmp/pear/temp/uv/php_uv.c:1545:2: error: lvalue required as increment operand
  ++GC_REFCOUNT(&uv->std);
  ^~
/tmp/pear/temp/uv/php_uv.c: In function 'php_uv_read_cb':
/tmp/pear/temp/uv/php_uv.c:1588:24: error: lvalue required as increment operand
   GC_REFCOUNT(&uv->std)++;
                        ^~
/tmp/pear/temp/uv/php_uv.c: In function 'php_uv_prepare_cb':
/tmp/pear/temp/uv/php_uv.c:1662:23: error: lvalue required as increment operand
  GC_REFCOUNT(&uv->std)++;
                       ^~
/tmp/pear/temp/uv/php_uv.c: In function 'php_uv_check_cb':
/tmp/pear/temp/uv/php_uv.c:1683:23: error: lvalue required as increment operand
  GC_REFCOUNT(&uv->std)++;
                       ^~
/tmp/pear/temp/uv/php_uv.c: In function 'php_uv_async_cb':
/tmp/pear/temp/uv/php_uv.c:1705:23: error: lvalue required as increment operand
  GC_REFCOUNT(&uv->std)++;
                       ^~
/tmp/pear/temp/uv/php_uv.c: In function 'php_uv_fs_event_cb':
/tmp/pear/temp/uv/php_uv.c:1908:23: error: lvalue required as increment operand
  GC_REFCOUNT(&uv->std)++;
                       ^~
/tmp/pear/temp/uv/php_uv.c: In function 'php_uv_fs_poll_cb':
/tmp/pear/temp/uv/php_uv.c:1963:23: error: lvalue required as increment operand
  GC_REFCOUNT(&uv->std)++;
                       ^~
/tmp/pear/temp/uv/php_uv.c: In function 'php_uv_poll_cb':
/tmp/pear/temp/uv/php_uv.c:1989:24: error: lvalue required as increment operand
   GC_REFCOUNT(&uv->std)++;
                        ^~
/tmp/pear/temp/uv/php_uv.c: In function 'php_uv_udp_recv_cb':
/tmp/pear/temp/uv/php_uv.c:2021:23: error: lvalue required as increment operand
  GC_REFCOUNT(&uv->std)++;
                       ^~
/tmp/pear/temp/uv/php_uv.c: In function 'php_uv_close':
/tmp/pear/temp/uv/php_uv.c:2080:3: error: lvalue required as increment operand
   ++GC_REFCOUNT(&uv->std);
   ^~
/tmp/pear/temp/uv/php_uv.c: In function 'php_uv_idle_cb':
/tmp/pear/temp/uv/php_uv.c:2098:23: error: lvalue required as increment operand
  GC_REFCOUNT(&uv->std)++;
                       ^~
/tmp/pear/temp/uv/php_uv.c: In function 'php_uv_timer_cb':
/tmp/pear/temp/uv/php_uv.c:2166:24: error: lvalue required as increment operand
   GC_REFCOUNT(&uv->std)++;
                        ^~
/tmp/pear/temp/uv/php_uv.c: In function 'php_uv_signal_cb':
/tmp/pear/temp/uv/php_uv.c:2186:23: error: lvalue required as increment operand
  GC_REFCOUNT(&uv->std)++;
                       ^~
/tmp/pear/temp/uv/php_uv.c: In function 'php_uv_udp_send':
/tmp/pear/temp/uv/php_uv.c:2346:23: error: lvalue required as increment operand
  GC_REFCOUNT(&uv->std)++;
                       ^~
/tmp/pear/temp/uv/php_uv.c: In function 'php_uv_tcp_connect':
/tmp/pear/temp/uv/php_uv.c:2375:23: error: lvalue required as increment operand
  GC_REFCOUNT(&uv->std)++;
                       ^~
/tmp/pear/temp/uv/php_uv.c: In function 'zif_uv_signal_start':
/tmp/pear/temp/uv/php_uv.c:3498:23: error: lvalue required as increment operand
  GC_REFCOUNT(&uv->std)++;
                       ^~
/tmp/pear/temp/uv/php_uv.c: In function 'zif_uv_write':
/tmp/pear/temp/uv/php_uv.c:3612:24: error: lvalue required as increment operand
   GC_REFCOUNT(&uv->std)++;
                        ^~
/tmp/pear/temp/uv/php_uv.c: In function 'zif_uv_write2':
/tmp/pear/temp/uv/php_uv.c:3645:24: error: lvalue required as increment operand
   GC_REFCOUNT(&uv->std)++;
                        ^~
/tmp/pear/temp/uv/php_uv.c: In function 'zif_uv_shutdown':
/tmp/pear/temp/uv/php_uv.c:3713:23: error: lvalue required as increment operand
  GC_REFCOUNT(&uv->std)++;
                       ^~
/tmp/pear/temp/uv/php_uv.c: In function 'zif_uv_read_start':
/tmp/pear/temp/uv/php_uv.c:3776:23: error: lvalue required as increment operand
  GC_REFCOUNT(&uv->std)++;
                       ^~
/tmp/pear/temp/uv/php_uv.c: In function 'zif_uv_listen':
/tmp/pear/temp/uv/php_uv.c:3901:23: error: lvalue required as increment operand
  GC_REFCOUNT(&uv->std)++;
                       ^~
/tmp/pear/temp/uv/php_uv.c: In function 'zif_uv_timer_start':
/tmp/pear/temp/uv/php_uv.c:3985:23: error: lvalue required as increment operand
  GC_REFCOUNT(&uv->std)++;
                       ^~
/tmp/pear/temp/uv/php_uv.c: In function 'zif_uv_timer_again':
/tmp/pear/temp/uv/php_uv.c:4034:23: error: lvalue required as increment operand
  GC_REFCOUNT(&uv->std)++;
                       ^~
/tmp/pear/temp/uv/php_uv.c: In function 'zif_uv_idle_start':
/tmp/pear/temp/uv/php_uv.c:4113:23: error: lvalue required as increment operand
  GC_REFCOUNT(&uv->std)++;
                       ^~
/tmp/pear/temp/uv/php_uv.c: In function 'zif_uv_default_loop':
/tmp/pear/temp/uv/php_uv.c:4231:2: error: lvalue required as increment operand
  ++GC_REFCOUNT(&loop->std);
  ^~
/tmp/pear/temp/uv/php_uv.c: In function 'zif_uv_udp_recv_start':
/tmp/pear/temp/uv/php_uv.c:4308:23: error: lvalue required as increment operand
  GC_REFCOUNT(&uv->std)++;
                       ^~
/tmp/pear/temp/uv/php_uv.c: In function 'zif_uv_pipe_connect':
/tmp/pear/temp/uv/php_uv.c:4630:23: error: lvalue required as increment operand
  GC_REFCOUNT(&uv->std)++;
                       ^~
/tmp/pear/temp/uv/php_uv.c: In function 'zif_uv_spawn':
/tmp/pear/temp/uv/php_uv.c:5092:3: error: lvalue required as increment operand
   ++GC_REFCOUNT(&proc->std);
   ^~
/tmp/pear/temp/uv/php_uv.c: In function 'zif_uv_prepare_start':
/tmp/pear/temp/uv/php_uv.c:5343:23: error: lvalue required as increment operand
  GC_REFCOUNT(&uv->std)++;
                       ^~
/tmp/pear/temp/uv/php_uv.c: In function 'zif_uv_check_start':
/tmp/pear/temp/uv/php_uv.c:5420:23: error: lvalue required as increment operand
  GC_REFCOUNT(&uv->std)++;
                       ^~
/tmp/pear/temp/uv/php_uv.c: In function 'zif_uv_poll_start':
/tmp/pear/temp/uv/php_uv.c:5992:24: error: lvalue required as increment operand
   GC_REFCOUNT(&uv->std)++;
                        ^~
/tmp/pear/temp/uv/php_uv.c: In function 'zif_uv_fs_poll_start':
/tmp/pear/temp/uv/php_uv.c:6063:23: error: lvalue required as increment operand
  GC_REFCOUNT(&uv->std)++;
                       ^~
Makefile:195: recipe for target 'php_uv.lo' failed
make: *** [php_uv.lo] Error 1
ERROR: `make' failed
The command '/bin/sh -c bash build/install.sh' returned a non-zero code: 1
```

**Comment by torinaki** [comment]
I'm using the following branch of PHP version:
https://github.com/zendtech/php-src/tree/jit-dynasm/

**Comment by bwoebi** [comment]
You are not using master, right? The current release will only work with up to 7.2 inclusive. Use master for compatibility with php-src/master (including the jit-dynasm branch).

**Comment by torinaki** [comment]
@bwoebi thanks you. It helps :)
